"""add groups and chatbot tables

Revision ID: 72108464a6d8
Revises: c321a2bf380b
Create Date: 2025-12-06 16:27:52.696830

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '72108464a6d8'
down_revision: Union[str, None] = 'c321a2bf380b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
