"""add_banner_image_to_users

Revision ID: 9316d8665695
Revises: 72108464a6d8
Create Date: 2025-12-07 23:51:40.190637

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9316d8665695'
down_revision: Union[str, None] = '72108464a6d8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('banner_image', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'banner_image')
    # ### end Alembic commands ###
